import type { Metadata } from "next";
import "./globals.css";
import { SfProDisplay } from "sf-pro/display";
import { ReactNode } from "react";
import NavigationWeb from "@/components/navigation/web/navigation-web";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
  auth
}: {
  children: ReactNode;
  auth: ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${SfProDisplay.className} antialiased`}
      >
        <NavigationWeb />
        {children}
        {auth}


      </body>
    </html>
  );
}
